---
- name: Install node and npm
  hosts: webserver
  tasks:
    - name: Update repo and 
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Install node js and npm
      apt: 
        pkg: 
          - nodejs
          - npm
- name: Deploy nodejs app
  hosts: webserver
  tasks:
    - name: Copy file 
      copy: 
        src: './simple-nodejs/nodejs-app-1.0.0.tgz'
        dest: '/root/'
    - name: Create dir
      file:
        path: '/root/simple-nodejs/'
        state: directory
    - name: Upack the nodejs tar file
      unarchive: 
        src: '/root/nodejs-app-1.0.0.tgz'
        dest: '/root/simple-nodejs/'
        remote_src: yes


      